default: &default
  adapter: postgresql
  encoding: unicode
development:
  <<: *default
  database: minifacebook_app
  username: postgres
  # password: root
 

production:
  <<: *default
  database: minifacebook_app
  username: root
  password: root